'use strict';
const Homey = require('homey');
const { BudbeeApi } = require('../../lib/budbee-api');
function codes(s) { try { const a = JSON.parse(s.tracking_numbers_json || '[]'); return Array.isArray(a) ? a : []; } catch (_) { return []; } }
function val(o, ...ks) { for (const k of ks) if (o && o[k] != null) return o[k]; return ''; }
module.exports = class BudbeeDevice extends Homey.Device {
  async onInit() { this._packages = []; this._timer = this.homey.setInterval(() => this.refresh(false), 15 * 60 * 1000); this.homey.setTimeout(() => this.refresh(true), 3000); }
  async onDeleted() { if (this._timer) this.homey.clearInterval(this._timer); }
  async refresh() { const api = new BudbeeApi(); const rows = []; for (const code of codes(this.getSettings())) { try { const p = await api.parcel(code); if (!p) continue; const rawStatus = val(p, 'state', 'status', 'statusName') || val(p.consignment, 'status') || val(p.meta, 'type') || 'In transit'; const st = typeof rawStatus === 'object' ? (rawStatus.name || rawStatus.status || JSON.stringify(rawStatus)) : String(rawStatus); const delivered = /picked.?up|delivered|levererad|bezorgd/i.test(st); const win = p.delivery?.timeInterval || p.timeInterval || p.estimatedDeliveryTime || p.deliveryWindow || {}; const from = val(win, 'start', 'from'); const to = val(win, 'stop', 'to'); rows.push({ id: code, tracking: code, sender: p.brand?.name || p.brand || 'Budbee', status: st, deliveryDate: val(p, 'estimatedDeliveryDate', 'deliveryDate') || from || '', deliveryWindow: typeof win === 'string' ? win : [from, to].filter(Boolean).join(' - '), updatedAt: new Date().toISOString(), delivered, detailsUrl: `https://track.budbee.com/${encodeURIComponent(code)}` }); } catch (e) { this.error(`Budbee ${code}:`, e); } }
    const previous=new Map((this._packages||[]).map(x=>[x.tracking,x])); this._packages = rows; for(const p of rows){const old=previous.get(p.tracking);const tokens={tracking:p.tracking||'',status:p.status||''};if(!old)await this.homey.flow.getDeviceTriggerCard('budbee_new_package').trigger(this,tokens,{}).catch(()=>{});else if(old.status!==p.status)await this.homey.flow.getDeviceTriggerCard('budbee_status_changed').trigger(this,{...tokens,previous_status:old.status||''},{}).catch(()=>{})} await this.setCapabilityValue('budbee_parcel_count', rows.filter(x => !x.delivered).length); await this.setCapabilityValue('budbee_status', rows[0]?.status || 'Connected'); await this.setCapabilityValue('budbee_last_update', new Date().toISOString()); await this.setAvailable(); return true; }
  getWidgetData() { return { parcels: this._packages || [], authenticated: true, carrier: 'budbee' }; }
};