'use strict';
const Homey=require('homey');const crypto=require('crypto');const {BpostApi}=require('../../lib/bpost-api');
function parse(v){return String(v||'').split(/\n+/).map(x=>x.trim()).filter(Boolean).map(line=>{const p=line.split('|').map(x=>x.trim());return{barcode:p[0],postalCode:p[1]||''}}).filter(x=>x.barcode)}
module.exports=class BpostDriver extends Homey.Driver{
 async onInit(){this.homey.flow.getConditionCard('bpost_packages_underway').registerRunListener(async({device})=>(device.getCapabilityValue('bpost_parcel_count')||0)>0);this.homey.flow.getConditionCard('bpost_account_connected').registerRunListener(async({device})=>device.getCapabilityValue('bpost_account_status')==='Connected');this.homey.flow.getActionCard('bpost_refresh').registerRunListener(async({device})=>device.refresh(true))}
 async onPair(s){
  s.setHandler('connect',async({email,password})=>{if(!email||!password)throw new Error('Enter your My bpost e-mail address and password.');const api=new BpostApi({email,password});await api.accountParcels();const id=crypto.createHash('sha1').update(email.toLowerCase()).digest('hex').slice(0,20);return{device:{name:'bpost',data:{id:`bpost-account-${id}`},settings:{account_email:email,account_password:password,tracking_numbers_json:'[]'},capabilities:["bpost_parcel_count", "bpost_total_count", "bpost_status", "bpost_tracking", "bpost_sender", "bpost_delivery_date", "bpost_delivery_window", "bpost_delivery_point", "bpost_weight", "bpost_product", "bpost_partner", "bpost_last_event", "bpost_account_status", "bpost_last_update"]}}});
  s.setHandler('manual_connect',async({trackingCodes})=>{const rows=parse(trackingCodes);if(!rows.length)throw new Error('Enter at least one bpost barcode.');const p=await new BpostApi().publicParcel(rows[0].barcode,rows[0].postalCode);if(!p)throw new Error('bpost does not know this barcode yet.');return{device:{name:'bpost',data:{id:`bpost-manual-${crypto.randomBytes(8).toString('hex')}`},settings:{account_email:'',account_password:'',tracking_numbers_json:JSON.stringify(rows)},capabilities:["bpost_parcel_count", "bpost_total_count", "bpost_status", "bpost_tracking", "bpost_sender", "bpost_delivery_date", "bpost_delivery_window", "bpost_delivery_point", "bpost_weight", "bpost_product", "bpost_partner", "bpost_last_event", "bpost_account_status", "bpost_last_update"]}}});
 }
 async onRepair(s){s.setHandler('connect',async({email,password})=>{const d=s.getDevice();await new BpostApi({email,password}).accountParcels();await d.setSettings({account_email:email,account_password:password});await d.refresh(true);return true});s.setHandler('manual_connect',async({trackingCodes})=>{const d=s.getDevice();await d.setSettings({tracking_numbers_json:JSON.stringify(parse(trackingCodes))});await d.refresh(true);return true})}
};