'use strict';
const Homey=require('homey');const {DpdApi}=require('../../lib/dpd-api');
function arr(v){return Array.isArray(v)?v:[]}
module.exports=class DpdDevice extends Homey.Device{
 async onInit(){this._packages=[];this._previous=new Map();this._timer=this.homey.setInterval(()=>this.refresh(false),15*60*1000);this.homey.setTimeout(()=>this.refresh(true),3000)}
 async onDeleted(){if(this._timer)this.homey.clearInterval(this._timer)}
 async notifyAuth(){if(this.getStoreValue('authExpiredNotified')===true)return;await this.homey.notifications.createNotification({excerpt:`Reconnect DPD – the credentials for ${this.getName()} no longer work. Repair the DPD device.`}).catch(()=>{});await this.setStoreValue('authExpiredNotified',true)}
 async refresh(){const s=this.getSettings();try{const api=new DpdApi(s.email,s.password,s.bu||'DPD-NL');const data=await api.parcels();let incoming=arr(data.incomingShipments||data.incomingParcels||data.parcels);let outgoing=arr(data.sendingShipments||data.sendingParcels);let all=[...incoming,...outgoing];const previous=new Map((this._packages||[]).map(x=>[x.tracking,x]));this._packages=all.map((p,i)=>{let st=p.status?.description||p.statusDescription||p.status||p.parcelStatus||'';if(typeof st==='object')st=st.description||st.code||'';let track=p.parcelNumber||p.parcelNo||p.barcode||p.id||String(i);return {id:track,tracking:track,sender:p.sender?.name||p.shipperName||p.senderName||'DPD',status:String(st),deliveryDate:p.deliveryDate||p.plannedDeliveryDate||p.deliveryTime||'',deliveryWindow:p.deliveryTimeRange||'',updatedAt:new Date().toISOString(),delivered:/deliver|bezorg|zugestellt/i.test(String(st)),detailsUrl:`https://www.dpdgroup.com/nl/mydpd/my-parcels/search?parcelNumber=${encodeURIComponent(track)}`}});for(const p of this._packages){const old=previous.get(p.tracking);const tokens={tracking:p.tracking||'',status:p.status||''};if(!old)await this.homey.flow.getDeviceTriggerCard('dpd_new_package').trigger(this,tokens,{}).catch(()=>{});else if(old.status!==p.status)await this.homey.flow.getDeviceTriggerCard('dpd_status_changed').trigger(this,{...tokens,previous_status:old.status||''},{}).catch(()=>{})}await this.setCapabilityValue('dpd_parcel_count',this._packages.filter(p=>!p.delivered).length);await this.setCapabilityValue('dpd_status',this._packages.length?this._packages[0].status:'Connected');await this.setCapabilityValue('dpd_last_update',new Date().toISOString());await this.setStoreValue('authExpiredNotified',false);await this.setAvailable();return true}catch(e){if([400,401,403].includes(e.status)||/login|auth|credential/i.test(e.message)){await this.notifyAuth();await this.setUnavailable('DPD login expired').catch(()=>{})}this.error(e);return false}}
 getWidgetData(){return {parcels:this._packages||[],authenticated:this.getStoreValue('authExpiredNotified')!==true,carrier:'dpd'}}
};