'use strict';
class UpsApiError extends Error{constructor(message,status=0,body=null,path=''){super(message);this.name='UpsApiError';this.status=status;this.body=body;this.path=path}}
const PPC='https://webapis.ups.com',INCOMING='/ppc/api/AccountDashboard/GetIncomingShipments';
function b64urlDecode(v){let s=String(v||'').replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Buffer.from(s,'base64').toString('utf8')}
function parseCallback(value){const raw=String(value||'').trim();if(!raw)throw new UpsApiError('UPS login data is empty.');let u;try{u=new URL(raw)}catch(_){throw new UpsApiError('Invalid UPS login data.')}if(u.protocol!=='ups:'||u.hostname!=='login')throw new UpsApiError('Invalid UPS login data.');const q=u.searchParams,mode=q.get('mode')||'';if(mode==='web_session'){let bundle;try{bundle=JSON.parse(b64urlDecode(q.get('bundle')))}catch(_){throw new UpsApiError('Invalid UPS PPC session bundle.')}if(!bundle?.cookies?.length||!bundle?.requests?.[INCOMING])throw new UpsApiError('UPS PPC session bundle is incomplete.');return{raw,mode,bundle}}throw new UpsApiError('Use UPS Token Helper 0.1.5 or newer.')}
async function read(r){const t=await r.text();try{return t?JSON.parse(t):{}}catch(_){return{text:t}}}
function splitSetCookie(v){if(!v)return[];return String(v).split(/,(?=\\s*[^;,=\\s]+=[^;,]+)/g)}
function cookiePair(s){const first=String(s||'').split(';',1)[0],i=first.indexOf('=');return i>0?[first.slice(0,i).trim(),first.slice(i+1).trim()]:null}
class UpsApi{
 constructor({sessionBundle=null}={}){this.sessionBundle=sessionBundle;this.cookies=new Map();for(const c of sessionBundle?.cookies||[])if(c?.name)this.cookies.set(c.name,String(c.value??''))}
 cookieHeader(){return[...this.cookies].map(([k,v])=>`${k}=${v}`).join('; ')}
 absorbCookies(r){let values=[];if(typeof r.headers.getSetCookie==='function')values=r.headers.getSetCookie();else values=splitSetCookie(r.headers.get('set-cookie'));for(const sc of values){const p=cookiePair(sc);if(p)this.cookies.set(p[0],p[1])}}
 headersFor(path){const saved=this.sessionBundle?.headers?.[path]||{},h={'Accept':saved.accept||'application/json, text/plain, */*','Content-Type':saved['content-type']||'application/json','Origin':'https://www.ups.com','Referer':'https://www.ups.com/ppc/dashboard.html','Cookie':this.cookieHeader(),'User-Agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/153.0.0.0 Safari/537.36'};for(const k of ['x-xsrf-token','x-csrf-token','x-requested-with','x-ups-locale','x-ups-country','accept-language'])if(saved[k])h[k]=saved[k];return h}
 async ppc(path){const b=this.sessionBundle;if(!b)throw new UpsApiError('UPS PPC session is missing.',422,null,path);const tpl=b.requests?.[path]||{method:'POST',body:''},opts={method:'POST',headers:this.headersFor(path),redirect:'follow'};if(tpl.body!==undefined&&tpl.body!==null&&tpl.body!=='')opts.body=tpl.body;let r;try{r=await fetch(PPC+path,opts)}catch(e){throw new UpsApiError(`UPS network error at ${path}: ${e.message}`,0,null,path)}this.absorbCookies(r);const d=await read(r);if(!r.ok){const msg=d?.message||d?.error_description||d?.error||d?.text||`HTTP ${r.status}`;throw new UpsApiError(`UPS ${path}: ${String(msg).slice(0,220)}`,r.status,d,path)}return d}
 async incoming(){try{return await this.ppc(INCOMING)}catch(first){if(![400,401,403,419,440].includes(first.status))throw first;for(const p of ['/ppc/api/init/gettoken','/ppc/api/Profile/InitSession','/ppc/api/MyChoice/GetEnrollmentsRequest/','/ppc/api/MyChoice/GetEnrollmentInformation/'])if(this.sessionBundle?.requests?.[p])await this.ppc(p);return this.ppc(INCOMING)}}
}
module.exports={UpsApi,UpsApiError,parseCallback};
