'use strict';
const { tr } = require('../../lib/i18n.js');
// User-facing widget texts (all 13 app languages; English is the fallback).
const SELECT_DEVICE = { en: 'Select a {carrier} device for this widget.', nl: 'Selecteer een {carrier}-apparaat voor deze widget.', de: 'Wähle ein {carrier}-Gerät für dieses Widget.', fr: 'Sélectionnez un appareil {carrier} pour ce widget.', it: 'Seleziona un dispositivo {carrier} per questo widget.', sv: 'Välj en {carrier}-enhet för den här widgeten.', no: 'Velg en {carrier}-enhet for denne widgeten.', es: 'Selecciona un dispositivo de {carrier} para este widget.', da: 'Vælg en {carrier}-enhed til denne widget.', ru: 'Выберите устройство {carrier} для этого виджета.', pl: 'Wybierz urządzenie {carrier} dla tego widżetu.', ko: '이 위젯에 사용할 {carrier} 기기를 선택하세요.', ar: 'اختر جهاز {carrier} لهذه الأداة.' };
const PARCEL_TYPE = { en: 'Parcel', nl: 'Pakket', de: 'Paket', fr: 'Colis', it: 'Pacco', sv: 'Paket', no: 'Pakke', es: 'Paquete', da: 'Pakke', ru: 'Посылка', pl: 'Paczka', ko: '택배', ar: 'طرد' };
const localizePackageStatus = require('../../lib/status-i18n');
function ids(v){if(Array.isArray(v))return v.map(String).filter(Boolean);if(typeof v!=='string')return[];return v.split(',').map(x=>x.trim()).filter(Boolean)}
function str(...v){for(const x of v){if(x===0)return'0';if(x!==undefined&&x!==null&&String(x).trim())return String(x).trim()}return''}
function shipmentType(homey,value){const raw=str(value);if(!raw)return'';return /^parcel$/i.test(raw)?tr(homey,PARCEL_TYPE):raw}
function device(homey,raw){const wanted=ids(raw),list=homey.drivers.getDriver('postnl').getDevices(),id=wanted[0]||String(raw||'').trim(),d=list.find(x=>x.getId()===id);if(!d)throw new Error(tr(homey,SELECT_DEVICE,{carrier:'PostNL'}));return d}
function rank(p){const raw=p?.deliveryWindowFrom||p?.deliveryDate||p?.createdAt||'';const t=Date.parse(raw);return Number.isFinite(t)?t:Number.MAX_SAFE_INTEGER}
module.exports={
 async getData({homey,query}){const d=device(homey,query?.deviceIds||query?.deviceId),data=d.getWidgetData(),active=(data.packages||[]).filter(p=>!p.delivered).sort((a,b)=>rank(a)-rank(b))[0]||null;return{authenticated:data.authenticated,locale:homey.i18n.getLanguage(),timeZone:homey.clock.getTimezone(),updatedAt:data.updatedAt||null,parcel:active?{id:str(active.id),sender:str(active.sender,active.title,active.sourceDisplayName,'PostNL'),tracking:str(active.barcode,active.id),status:str(active.statusRaw,active.latestStatusEvent,localizePackageStatus(homey,active.status||''),active.status),deliveryDate:str(active.deliveryDate,active.deliveryWindowFrom),deliveryWindow:str(active.deliveryWindow),deliveryWindowFrom:str(active.deliveryWindowFrom),deliveryWindowTo:str(active.deliveryWindowTo),detailsUrl:str(active.detailsUrl),createdAt:str(active.createdAt),shipmentType:shipmentType(homey,active.shipmentType),direction:str(active.direction)}:null}},
 async sync({homey,body}){const d=device(homey,body?.deviceIds||body?.deviceId);await d.sync({reason:'widget',force:true});return{ok:true}}
};
