const localizePackageStatus = require('../../lib/status-i18n.js');
'use strict';
const Homey=require('homey'),API=require('../../lib/post-dhl-de-api');
function arr(v){if(Array.isArray(v))return v;if(v&&typeof v==='object'){for(const k of ['shipments','items','currentShipments','sendungen'])if(Array.isArray(v[k]))return v[k]}return[]}
function first(o,keys){for(const k of keys){const v=k.split('.').reduce((a,x)=>a?.[x],o);if(v!==undefined&&v!==null&&v!=='')return v}return''}
module.exports=class extends Homey.Device{
 async onInit(){this.snapshot=this.getStoreValue('snapshot')||{parcels:[],letters:[]};await this.apply();this.timer=this.homey.setInterval(()=>this.refresh().catch(this.error),5*60*1000);this.homey.setTimeout(()=>this.refresh().catch(this.error),5000)}
 async onUninit(){if(this.timer)this.homey.clearInterval(this.timer)}
 api(){return new API({accessToken:this.getStoreValue('access_token'),refreshToken:this.getStoreValue('refresh_token'),expiresAt:this.getStoreValue('expires_at')||0})}
 async saveApi(a){await this.setStoreValue('access_token',a.accessToken);await this.setStoreValue('refresh_token',a.refreshToken);await this.setStoreValue('expires_at',a.expiresAt)}
 async updateTokens(t,e){await this.setStoreValue('access_token',t.accessToken);await this.setStoreValue('refresh_token',t.refreshToken);await this.setStoreValue('expires_at',e);await this.refresh(true)}
 normalize(raw){return arr(raw).map((p,i)=>({id:String(first(p,['id','shipmentId','pieceCode','shipmentNumber'])||i),tracking:String(first(p,['shipmentNumber','pieceCode','id'])||''),sender:String(first(p,['sender.name','sender','shipper.name','shipper'])||''),status:String(first(p,['status.status','status','statusText','shortStatus'])||''),deliveryDate:first(p,['deliveryDate','delivery.date','expectedDeliveryDate','deliveryTime']),deliveryWindow:String(first(p,['deliveryTimeframe','delivery.window','timeframe'])||''),updatedAt:first(p,['lastUpdate','timestamp','updatedAt'])||new Date().toISOString(),raw:p}))}
 async refresh(){const a=this.api();try{const [raw,info]=await Promise.all([a.shipments(),a.customer().catch(()=>({}))]);await this.saveApi(a);const parcels=this.normalize(raw),letters=await a.letters();this.snapshot={parcels,letters,updatedAt:new Date().toISOString(),mailStatus:'endpoint_pending'};await this.setStoreValue('snapshot',this.snapshot);if(info.postNumber)await this.setStoreValue('postnumber',info.postNumber);await this.setAvailable();await this.apply();return this.snapshot}catch(e){if([401,403].includes(e.status))await this.setUnavailable('Post & DHL login expired').catch(()=>{});throw e}}
 async apply(){const p=this.snapshot.parcels||[],l=this.snapshot.letters||[],lang=this.homey.i18n.getLanguage(),updated=this.snapshot.updatedAt?new Intl.DateTimeFormat(lang==='nl'?'nl-NL':lang==='de'?'de-DE':'en-GB',{timeZone:this.homey.clock.getTimezone(),dateStyle:'short',timeStyle:'short'}).format(new Date(this.snapshot.updatedAt)):'—';const next=p.map(x=>x.deliveryDate).filter(Boolean).sort()[0]||'—';const vals={dhl_de_parcel_count:p.length,dhl_de_mail_count:l.length,dhl_de_status:p.length?`${p.length} ${lang==='de'?'Pakete':lang==='nl'?'pakketten':'packages'}`:(lang==='de'?'Keine Pakete':lang==='nl'?'Geen pakketten':'No packages'),dhl_de_next_delivery:next,dhl_de_postnumber:this.getStoreValue('postnumber')||'—',dhl_de_account_status:this.homey.app.getConnectionLabel(Boolean(this.getStoreValue('access_token'))),dhl_de_mail_status:lang==='de'?'API-Erfassung erforderlich':lang==='nl'?'API-capture vereist':'API capture required',dhl_de_last_update:updated};for(const[k,v]of Object.entries(vals))if(this.hasCapability(k))await this.setCapabilityValue(k,v).catch(this.error)}
 getWidgetData(){return{parcels:this.snapshot.parcels||[],letters:this.snapshot.letters||[],mailStatus:this.snapshot.mailStatus||'endpoint_pending',authenticated:Boolean(this.getStoreValue('access_token'))}}
};