const localizePackageStatus = require('../../lib/status-i18n.js');
'use strict';
const Homey=require('homey');const {FedExApi}=require('../../lib/fedex-api');
function nums(s){try{const a=JSON.parse(s.tracking_numbers_json||'[]');return Array.isArray(a)?a:[]}catch{return[]}}
function parse(d,fallback){const r=d?.output?.completeTrackResults?.[0]?.trackResults?.[0]||{};const status=r.latestStatusDetail?.description||r.derivedStatus||'Connected';const dates=Array.isArray(r.dateAndTimes)?r.dateAndTimes:[];const eta=dates.find(x=>/ESTIMATED_DELIVERY/i.test(String(x.type)))?.dateTime||'';const latestDate=dates.map(x=>String(x?.dateTime||'')).filter(Boolean).sort((a,b)=>(Date.parse(b)||0)-(Date.parse(a)||0))[0]||'';const tracking=r.trackingNumberInfo?.trackingNumber||fallback;const service=r.serviceDetail?.description||'';return{id:tracking,tracking,sender:r.shipperInformation?.contact?.companyName||service||'FedEx',status:String(status),deliveryDate:eta,deliveryWindow:'',service:String(service),lastEvent:String(status),lastEventAt:latestDate,updatedAt:latestDate||new Date().toISOString(),delivered:/delivered|bezorgd|afgeleverd/i.test(String(status)),detailsUrl:`https://www.fedex.com/fedextrack/?trknbr=${encodeURIComponent(tracking)}`}}
module.exports=class FedExDevice extends Homey.Device{
 async onInit(){this._packages=[];this._timer=this.homey.setInterval(()=>this.refresh(false),15*60*1000);this.homey.setTimeout(()=>this.refresh(true),3000)}
 async onDeleted(){if(this._timer)this.homey.clearInterval(this._timer)}
 async notifyAuth(){if(this.getStoreValue('authExpiredNotified')===true)return;await this.homey.notifications.createNotification({excerpt:`Reconnect FedEx – credentials for ${this.getName()} no longer work.`}).catch(()=>{});await this.setStoreValue('authExpiredNotified',true)}
 async refresh(){const s=this.getSettings(),api=new FedExApi({clientId:s.client_id,clientSecret:s.client_secret,accessToken:s.access_token,expiresAt:s.expires_at});try{const rows=[];for(const n of nums(s)){try{rows.push(parse(await api.track(n),n))}catch(e){if([400,401,403].includes(e.status))throw e;this.error(`FedEx ${n}:`,e)}}if(api.accessToken!==s.access_token||api.expiresAt!==s.expires_at)await this.setSettings({access_token:api.accessToken,expires_at:api.expiresAt});const prev=new Map((this._packages||[]).map(x=>[x.tracking,x]));this._packages=rows;for(const p of rows){const old=prev.get(p.tracking),t={tracking:p.tracking||'',status:localizePackageStatus(this.homey, p.status)||''};if(!old)await this.homey.flow.getDeviceTriggerCard('fedex_new_package').trigger(this,t,{}).catch(()=>{});else if(old.status!==p.status)await this.homey.flow.getDeviceTriggerCard('fedex_status_changed').trigger(this,{...t,previous_status:localizePackageStatus(this.homey,old.status)||''},{}).catch(()=>{})}await this.setCapabilityValue('fedex_parcel_count',rows.filter(x=>!x.delivered).length);await this.setCapabilityValue('fedex_status',rows[0]?.status?localizePackageStatus(this.homey,rows[0].status):(nums(s).length?'Connected':'Connected – add tracking numbers via Repair'));await this.setCapabilityValue('fedex_last_update',new Date().toISOString());await this.setStoreValue('authExpiredNotified',false);await this.setAvailable();return true}catch(e){if([400,401,403].includes(e.status)||/auth|credential|client|oauth/i.test(e.message)){await this.notifyAuth();await this.setUnavailable('FedEx authorization failed').catch(()=>{})}this.error(e);return false}}
 getWidgetData(){return{parcels:this._packages||[],authenticated:this.getStoreValue('authExpiredNotified')!==true,carrier:'fedex'}}
};