const localizePackageStatus = require('../../lib/status-i18n.js');
'use strict';
const Homey=require('homey');const {GlsApi}=require('../../lib/gls-api');
function id(x){return x.TrackID||x.trackID||x.ParcelNumber||x.parcelNumber||x.ParcelNo||x.parcelNo||x.ShipmentUnitReference||x.shipmentUnitReference||''}
function parse(d,fallback){const r=Array.isArray(d)?(d[0]||{}):(d?.UnitDetail||d?.unitDetail||d?.parcel||d?.data||d||{}),events=r.Events||r.events||[],last=Array.isArray(events)&&events.length?events[events.length-1]:{},status=r.Status||r.status||r.State||r.state||last.DescriptionEN||last.descriptionEN||last.DescriptionNL||last.descriptionNL||'Connected',eta=r.Eta||r.eta||{},tracking=id(r)||fallback;return{id:tracking,tracking,sender:r.CustomerReference||r.customerReference||r.Shipper?.ContactID||'GLS',status:String(status),deliveryDate:eta.StartTime||eta.startTime||'',deliveryWindow:[eta.StartTime||eta.startTime,eta.EndTime||eta.endTime].filter(Boolean).join(' - '),updatedAt:last.Date||last.date||r.InitialDate||r.initialDate||new Date().toISOString(),delivered:/delivered|bezorgd|afgeleverd/i.test(String(status)),detailsUrl:r.Uri||r.uri||`https://gls-group.com/GROUP/en/parcel-tracking?match=${encodeURIComponent(tracking)}`}}
module.exports=class GlsDevice extends Homey.Device{
 async onInit(){this._packages=[];this._timer=this.homey.setInterval(()=>this.refresh(false),15*60*1000);this.homey.setTimeout(()=>this.refresh(true),3000)}
 async onDeleted(){if(this._timer)this.homey.clearInterval(this._timer)}
 async notifyAuth(){if(this.getStoreValue('authExpiredNotified')===true)return;await this.homey.notifications.createNotification({excerpt:`Reconnect GLS – credentials for ${this.getName()} no longer work.`}).catch(()=>{});await this.setStoreValue('authExpiredNotified',true)}
 async refresh(){const s=this.getSettings(),api=new GlsApi({username:s.username,password:s.password,subscriptionKey:s.subscription_key,trackUrlTemplate:s.track_url_template,parcelListUrl:s.parcel_list_url});try{const found=await api.findParcels(s.discovery_days||21),rows=[];for(const item of found){const n=id(item);if(!n)continue;try{rows.push(parse(await api.track(n),n))}catch(e){this.error(`GLS ${n}:`,e);rows.push(parse(item,n))}}const prev=new Map((this._packages||[]).map(x=>[x.tracking,x]));this._packages=rows;for(const p of rows){const old=prev.get(p.tracking),t={tracking:p.tracking||'',status:localizePackageStatus(this.homey, p.status)||''};if(!old)await this.homey.flow.getDeviceTriggerCard('gls_new_package').trigger(this,t,{}).catch(()=>{});else if(old.status!==p.status)await this.homey.flow.getDeviceTriggerCard('gls_status_changed').trigger(this,{...t,previous_status:localizePackageStatus(this.homey,old.status)||''},{}).catch(()=>{})}await this.setCapabilityValue('gls_parcel_count',rows.filter(x=>!x.delivered).length);await this.setCapabilityValue('gls_status',rows[0]?.status?localizePackageStatus(this.homey,rows[0].status):'Connected – no recent account shipments');await this.setCapabilityValue('gls_last_update',new Date().toISOString());await this.setStoreValue('authExpiredNotified',false);await this.setAvailable();return true}catch(e){if([400,401,403,490].includes(e.status)||/auth|credential|subscription|password/i.test(e.message)){await this.notifyAuth();await this.setUnavailable('GLS authorization failed').catch(()=>{})}this.error(e);return false}}
 getWidgetData(){return{parcels:this._packages||[],authenticated:this.getStoreValue('authExpiredNotified')!==true,carrier:'gls'}}
};